---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  # Apply to all namespaces except those exclicitly listed below
  mode: 'ON_WITH_EXCLUSION'
  exclusion:
    # Apply to all namespaces except istio-system and kube-system
    namespaces: ["istio-system","kube-system"]
